# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 06:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dojo', '0003_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dojo_post_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
